In [1]:
array1 = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [2]:
array2 = [1 2 3]

1×3 Array{Int64,2}:
 1  2  3

In [3]:
transpose(array1)

1×3 RowVector{Int64,Array{Int64,1}}:
 1  2  3

In [5]:
array1'

1×3 RowVector{Int64,Array{Int64,1}}:
 1  2  3

In [6]:
array1' == array2

true

In [7]:
array3 = [1,2,3.0]

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [8]:
array4 = [[1,2,3] [4,5,6] [7,8,9]]

3×3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

In [10]:
array5 = [[1 2 3]; [4 5 6]; [7 8 9]]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [11]:
length(array5)

9

In [13]:
for i in 1:length(array5)
    print("Element $(i) is $(array5[i]) \n")
end

Element 1 is 1 
Element 2 is 4 
Element 3 is 7 
Element 4 is 2 
Element 5 is 5 
Element 6 is 8 
Element 7 is 3 
Element 8 is 6 
Element 9 is 9 


In [14]:
array4' == array5

true

In [15]:
repmat([1,2],3)

6-element Array{Int64,1}:
 1
 2
 1
 2
 1
 2

In [16]:
repmat([1 2],3)

3×2 Array{Int64,2}:
 1  2
 1  2
 1  2

In [19]:
linspace(0, 11, 12)

0.0:1.0:11.0

In [20]:
array6 = collect(linspace(0, 11, 12))

12-element Array{Float64,1}:
  0.0
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0
 11.0

In [21]:
array7 = collect(logspace(2, 3))

50-element Array{Float64,1}:
  100.0  
  104.811
  109.854
  115.14 
  120.679
  126.486
  132.571
  138.95 
  145.635
  152.642
  159.986
  167.683
  175.751
    ⋮    
  596.362
  625.055
  655.129
  686.649
  719.686
  754.312
  790.604
  828.643
  868.511
  910.298
  954.095
 1000.0  

In [22]:
array8 = collect(range(0, 2, 10))

10-element Array{Int64,1}:
  0
  2
  4
  6
  8
 10
 12
 14
 16
 18

In [24]:
array9 = collect(0:5)

6-element Array{Int64,1}:
 0
 1
 2
 3
 4
 5

In [25]:
typeof(0:1:5)

StepRange{Int64,Int64}

In [26]:
typeof(0:5)

UnitRange{Int64}

In [27]:

array10 = Array{Integer}(3,3)

3×3 Array{Integer,2}:
 #undef  #undef  #undef
 #undef  #undef  #undef
 #undef  #undef  #undef

In [28]:
array11 = Array{Int64}(3,3)

3×3 Array{Int64,2}:
 4462516720  4433134224  4433134096
 4433133776  4433134288  4433757136
 4433134160  4433134032  4433133968

In [29]:
array8

10-element Array{Int64,1}:
  0
  2
  4
  6
  8
 10
 12
 14
 16
 18

In [33]:
reshape(array8, 4, 4)

LoadError: DimensionMismatch("new dimensions (4, 4) must be consistent with array size 10")

# Slicing

In [36]:
array12 = rand(10:20, 10, 5)

10×5 Array{Int64,2}:
 20  20  20  10  16
 18  10  12  10  17
 12  11  17  12  18
 13  16  16  10  16
 17  15  20  15  12
 14  17  17  14  16
 16  12  18  13  14
 11  20  13  10  19
 16  15  11  15  16
 20  17  19  10  18

In [39]:
array12[:,2]

10-element Array{Int64,1}:
 20
 10
 11
 16
 15
 17
 12
 20
 15
 17

In [40]:
array12[:, [2,5,3]]

10×3 Array{Int64,2}:
 20  16  20
 10  17  12
 11  18  17
 16  16  16
 15  12  20
 17  16  17
 12  14  18
 20  19  13
 15  16  11
 17  18  19

In [41]:
array12[:, 3:5]

10×3 Array{Int64,2}:
 20  10  16
 12  10  17
 17  12  18
 16  10  16
 20  15  12
 17  14  16
 18  13  14
 13  10  19
 11  15  16
 19  10  18

In [42]:
array12[[2, 4, 6], [1,5]]

3×2 Array{Int64,2}:
 18  17
 13  16
 14  16

In [47]:
array12[10, 1:end]

5-element Array{Int64,1}:
 20
 17
 19
 10
 18

In [48]:
find(array12)

50-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
  ⋮
 39
 40
 41
 42
 43
 44
 45
 46
 47
 48
 49
 50

In [51]:
array12[:, 3] .> 6

10-element BitArray{1}:
 true
 true
 true
 true
 true
 true
 true
 true
 true
 true

In [53]:
find(array12[:, 3] .> 15)

7-element Array{Int64,1}:
  1
  3
  4
  5
  6
  7
 10

# Modifications

In [54]:
array13 = [1, 2, 3, 4]

4-element Array{Int64,1}:
 1
 2
 3
 4

In [55]:
push!(array13,5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [56]:
array13

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [59]:
unshift!(array13, 0 )

6-element Array{Int64,1}:
 0
 1
 2
 3
 4
 5

In [61]:
pop!(array13)

5

In [62]:
array13

5-element Array{Int64,1}:
 0
 1
 2
 3
 4

In [64]:
shift!(array13)

0

In [65]:
array13

4-element Array{Int64,1}:
 1
 2
 3
 4

In [67]:
array13[2 ]= 1000

1000

In [68]:
array132

LoadError: UndefVarError: array132 not defined

In [69]:
array13

4-element Array{Int64,1}:
    1
 1000
    3
    4

# Comprehension

In [70]:
array14 = []

0-element Array{Any,1}

In [73]:
for i in 1:5
    push!(array14, 3*i)
end


In [74]:
array14

10-element Array{Any,1}:
 13
 13
 13
 13
 13
  3
  6
  9
 12
 15

In [75]:
array15 = [3 * i for i in 1:5]

5-element Array{Int64,1}:
  3
  6
  9
 12
 15

In [76]:
array14 == array15

false

In [77]:
[n^2 for n in 1:5]

5-element Array{Int64,1}:
  1
  4
  9
 16
 25

In [78]:
[a * b for a in 1:3, b in 1:3]

3×3 Array{Int64,2}:
 1  2  3
 2  4  6
 3  6  9

# Simple Calculation using Arrays

In [79]:
array15

5-element Array{Int64,1}:
  3
  6
  9
 12
 15

In [80]:
sum(array15)

45

In [81]:
mean(array15)

9.0

In [82]:
std(array15)

4.743416490252569

In [83]:
array16 = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [84]:
5+array16

3-element Array{Int64,1}:
 6
 7
 8

In [85]:
3*array16

3-element Array{Int64,1}:
 3
 6
 9

In [86]:
array17 = [4,5,6]

3-element Array{Int64,1}:
 4
 5
 6

In [87]:
array16 + array17

3-element Array{Int64,1}:
 5
 7
 9

In [88]:
array16 * array17

LoadError: DimensionMismatch("Cannot multiply two vectors")

In [89]:
array16 .* array17

3-element Array{Int64,1}:
  4
 10
 18

In [90]:
array16

3-element Array{Int64,1}:
 1
 2
 3

In [91]:
array17

3-element Array{Int64,1}:
 4
 5
 6

In [92]:
array16 * array17'

3×3 Array{Int64,2}:
  4   5   6
  8  10  12
 12  15  18

# NaN

In [93]:
typeof(NaN)

Float64

In [94]:
NaN == NaN

false

In [95]:
array18 = [1,2, NaN, 4,5]

5-element Array{Float64,1}:
   1.0
   2.0
 NaN  
   4.0
   5.0

In [96]:
sum(array18)

NaN

In [97]:
isnan.(array18)

5-element BitArray{1}:
 false
 false
  true
 false
 false

In [98]:
array19 = @data([1, 2, 3, 4,NA, 7, NA, 2])

LoadError: UndefVarError: @data not defined

In [5]:
using DataFrames

In [4]:
array19 = @data([1, 2, 3, 4,NA, 7, NA, 2])

LoadError: UndefVarError: @data not defined

In [3]:
array19

LoadError: UndefVarError: array19 not defined

In [13]:
using DataFrames

In [3]:
array19 = @data([1, 2, 3, 4,NA, 7, NA, 2])

LoadError: UndefVarError: @data not defined

In [14]:
Pkg.add("DataFrames")

INFO: Package DataFrames is already installed


In [1]:
Pkg.add("DataArrays")

INFO: Package DataArrays is already installed


In [2]:
using DataArrays, DataFrames

INFO: Precompiling module DataArrays.


In [17]:
df = DataFrame(x1=[1, 2], x2=["foo", "bar"])

2×2 DataFrames.DataFrame
│ Row │ x1 │ x2  │
├─────┼────┼─────┤
│ 1   │ 1  │ foo │
│ 2   │ 2  │ bar │

In [3]:
array19 = @data([1, 2, 3, 4,NA, 7, NA, 2])

8-element DataArrays.DataArray{Int64,1}:
 1       
 2       
 3       
 4       
  missing
 7       
  missing
 2       

# Tuples

In [19]:
tup = (1, 2, 3, "hello")

(1, 2, 3, "hello")

In [21]:
typeof(tup)

Tuple{Int64,Int64,Int64,String}

In [25]:
for i in 1:length(tup)
    println(" The value of the tuple at the index number $(i) is $(tup[i]) and the type is $(typeof(tup[i])).")
end


 The value of the tuple at the index number 1 is 1 and the type is Int64.
 The value of the tuple at the index number 2 is 2 and the type is Int64.
 The value of the tuple at the index number 3 is 3 and the type is Int64.
 The value of the tuple at the index number 4 is hello and the type is String.


In [26]:
a, b, c, seven = (1, 3, 5, 7)

(1, 3, 5, 7)

In [27]:
a

1

In [28]:
b

3

In [29]:
seven

7

In [30]:
tup2 = (1, 3, 5, 7, 9, 11, 13, 15);

In [31]:
tup2[end]

15

In [32]:
tup2[2:4]

(3, 5, 7)

In [33]:
tup2[end:-1:1]

(15, 13, 11, 9, 7, 5, 3, 1)

In [34]:
tup2[1] = 5

LoadError: MethodError: no method matching setindex!(::NTuple{8,Int64}, ::Int64, ::Int64)

In [35]:
tup3 = ((1, 2, 3), 1, 2, (3, 100, 1))

((1, 2, 3), 1, 2, (3, 100, 1))

In [36]:
tup3[1]

(1, 2, 3)

In [37]:
tup3[4][2]

100

# Dictionaries

In [38]:
dict1 = Dict(1 => 77, 2 => 66, 3 => 1)

Dict{Int64,Int64} with 3 entries:
  2 => 66
  3 => 1
  1 => 77

In [39]:
dict1 = Dict(Pair(1,100), Pair(2,200), Pair(3,300))

Dict{Int64,Int64} with 3 entries:
  2 => 200
  3 => 300
  1 => 100

In [40]:
dict2 = Dict{Any, Any}(1 => 77, 2 => 66, 3 => "three")

Dict{Any,Any} with 3 entries:
  2 => 66
  3 => "three"
  1 => 77

In [41]:
dict3 = Dict{Any, Any}("a" => 1, (2,3) => "hello")

Dict{Any,Any} with 2 entries:
  (2, 3) => "hello"
  "a"    => 1

In [43]:
dict4 = Dict(:A => 300, :B => 305, :C => 309)

Dict{Symbol,Int64} with 3 entries:
  :A => 300
  :B => 305
  :C => 309

In [45]:
dict4[:B]

305

In [46]:
get(dict4, :H, "Key does not exist")

"Key does not exist"

In [47]:
get(dict4, :B, "Key does not exist")

305

In [48]:
in((:A => 300), dict4)

true

In [49]:
haskey(dict4, :D)

false

In [50]:
dict4[:D] = 301

301

In [51]:
dict4

Dict{Symbol,Int64} with 4 entries:
  :A => 300
  :D => 301
  :B => 305
  :C => 309

In [52]:
delete!(dict4, :A)

Dict{Symbol,Int64} with 3 entries:
  :D => 301
  :B => 305
  :C => 309

In [53]:
keys(dict4)

Base.KeyIterator for a Dict{Symbol,Int64} with 3 entries. Keys:
  :D
  :B
  :C

In [54]:
values(dict4)

Base.ValueIterator for a Dict{Symbol,Int64} with 3 entries. Values:
  301
  305
  309

In [56]:
for (k, v) in dict4
    println("The key $(k) has value $(v)")
end

The key D has value 301
The key B has value 305
The key C has value 309


In [57]:
procedure_vals = ["Appendectomy", "Colectomy", "Cholecystectomy"]
procedure_dict = Dict{AbstractString,AbstractString}()

for (s, n) in enumerate(procedure_vals)
    procedure_dict["x_$(s)"] = n
end

In [58]:
procedure_dict

Dict{AbstractString,AbstractString} with 3 entries:
  "x_1" => "Appendectomy"
  "x_2" => "Colectomy"
  "x_3" => "Cholecystectomy"

In [61]:
for k in keys(procedure_dict)
    println(k, " is ", procedure_dict[k])
end

x_1 is Appendectomy
x_2 is Colectomy
x_3 is Cholecystectomy


In [63]:
for (k,v) in procedure_dict
    println(k, " is ", v)
end


x_1 is Appendectomy
x_2 is Colectomy
x_3 is Cholecystectomy


In [64]:
dict5 = Dict{AbstractString,Int16}("a" => 1,"b" =>2 ,"c" =>3 ,"d" =>4 ,"e" =>5 ,"f" =>6)

Dict{AbstractString,Int16} with 6 entries:
  "f" => 6
  "c" => 3
  "e" => 5
  "b" => 2
  "a" => 1
  "d" => 4

In [65]:
for k in sort(collect(keys(dict5)))
    println("$(k) is $(dict5[k])")
end


a is 1
b is 2
c is 3
d is 4
e is 5
f is 6


In [66]:
keys(dict5)

Base.KeyIterator for a Dict{AbstractString,Int16} with 6 entries. Keys:
  "f"
  "c"
  "e"
  "b"
  "a"
  "d"

In [67]:
collect(keys(dict5))

6-element Array{AbstractString,1}:
 "f"
 "c"
 "e"
 "b"
 "a"
 "d"

In [68]:
sort(collect(keys(dict5)))

6-element Array{AbstractString,1}:
 "a"
 "b"
 "c"
 "d"
 "e"
 "f"

# PRactice

In [69]:
a = [2 2 2]

1×3 Array{Int64,2}:
 2  2  2

In [70]:
a

1×3 Array{Int64,2}:
 2  2  2

In [71]:
typeof(a)

Array{Int64,2}

In [72]:
a = [[1, 2, 3] [4, 5, 6] ]
b = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [73]:
a'*b

2-element Array{Int64,1}:
 14
 32

In [74]:
repmat([1, 2], 3)

6-element Array{Int64,1}:
 1
 2
 1
 2
 1
 2

In [75]:
typeof(("A", 3, "B", 4, "C", 2))

Tuple{String,Int64,String,Int64,String,Int64}

In [77]:
my_dictionary = Dict([:A] => 200)

Dict{Array{Symbol,1},Int64} with 1 entry:
  Symbol[:A] => 200

In [78]:
my_dictionary

Dict{Array{Symbol,1},Int64} with 1 entry:
  Symbol[:A] => 200

In [79]:
get((:A, 200), my_dictionary)

LoadError: MethodError: no method matching get(::Tuple{Symbol,Int64}, ::Dict{Array{Symbol,1},Int64})
Closest candidates are:
  get(::ObjectIdDict, ::ANY, ::ANY) at associative.jl:434
  get(::Dict{K,V}, ::Any, ::Any) where {K, V} at dict.jl:478
  get(::Union{Function, Type}, ::Dict{K,V}, ::Any) where {K, V} at dict.jl:483
  ...

In [80]:
in((:A == 200), my_dictionary)

LoadError: Associative collections only contain Pairs;
Either look for e.g. A=>B instead, or use the `keys` or `values`
function if you are looking for a key or value respectively.

In [81]:
in(("A" = 200), my_dictionary)

LoadError: syntax: keyword argument is not a symbol: ""A""

In [82]:
in(("A" => 200), my_dictionary)

false

In [83]:
@time map(sin, collect(1:10000));

  0.102221 seconds (14.91 k allocations: 992.515 KiB)


In [84]:
@time map(sin, collect(1:10000));

  0.000224 seconds (11 allocations: 156.641 KiB)


# Function - Practice

In [85]:
function simple_addition(a, b = 1; c = 3)
  return a + b + c
end

simple_addition (generic function with 2 methods)

In [87]:
simple_addition(6) 

10

In [88]:
function simple_addition(a, b = 1; c = 3)
  return a + b + c
end

simple_addition (generic function with 2 methods)

In [89]:
simple_addition(3, 2)

8

In [90]:
function simple_addition{T <: Int}(x::T, y::T)
  return x + y
end

simple_addition (generic function with 3 methods)

In [91]:
simple_addition(5, 5)

10

In [92]:
simple_addition(x = 5, y = 5)

LoadError: MethodError: no method matching simple_addition(; x=5, y=5)
Closest candidates are:
  simple_addition(::T<:Int64, ::T<:Int64) where T<:Int64 at In[90]:2 got unsupported keyword arguments "x", "y"
  simple_addition(::Any) at In[88]:2 got unsupported keyword arguments "x", "y"
  simple_addition(::Any, ::Any; c) at In[88]:2 got unsupported keyword arguments "x", "y"

In [93]:
simple_addition(5., 5.)

13.0

In [94]:
simple_addition(5)

6

In [95]:
map(x -> 2x^2 + 3x - 2, 1:2:9)

5-element Array{Int64,1}:
   3
  25
  63
 117
 187

In [96]:
function my_function{T}(a::T, b::T, c::T = 2 + 8im)
  return a - (b * c)
end

my_function (generic function with 2 methods)

In [97]:
my_function(4, 3.5, 8)

LoadError: MethodError: no method matching my_function(::Int64, ::Float64, ::Int64)
Closest candidates are:
  my_function(::T, ::T, ::T) where T at In[96]:2
  my_function(::T, ::T) where T at In[96]:2

In [98]:
my_function(4, 3, 8)

-20

# DataFrames

In [11]:
df = DataFrame(Group=rand(["A", "B"], 20), Variable1=randn(20), Variable2=rand(20))

20×3 DataFrames.DataFrame
│ Row │ Group │ Variable1  │ Variable2 │
├─────┼───────┼────────────┼───────────┤
│ 1   │ B     │ -1.15627   │ 0.466338  │
│ 2   │ A     │ 0.710312   │ 0.799484  │
│ 3   │ B     │ 0.340343   │ 0.923127  │
│ 4   │ A     │ 1.73544    │ 0.280407  │
│ 5   │ A     │ -0.713845  │ 0.233645  │
│ 6   │ A     │ -0.441113  │ 0.372602  │
│ 7   │ B     │ -0.503066  │ 0.509483  │
│ 8   │ A     │ -0.145403  │ 0.856267  │
│ 9   │ B     │ -0.0278595 │ 0.929907  │
│ 10  │ B     │ 1.01364    │ 0.259262  │
│ 11  │ A     │ -1.09035   │ 0.720977  │
│ 12  │ A     │ -0.74815   │ 0.475484  │
│ 13  │ B     │ -2.14719   │ 0.636024  │
│ 14  │ B     │ 1.6768     │ 0.35738   │
│ 15  │ A     │ 0.175778   │ 0.271197  │
│ 16  │ B     │ -1.10938   │ 0.03964   │
│ 17  │ A     │ 1.38189    │ 0.0443877 │
│ 18  │ A     │ -1.06808   │ 0.511973  │
│ 19  │ A     │ -0.478153  │ 0.783339  │
│ 20  │ B     │ -1.86331   │ 0.627083  │

In [12]:
deleterows!(df,[3,5,9])

17×3 DataFrames.DataFrame
│ Row │ Group │ Variable1 │ Variable2 │
├─────┼───────┼───────────┼───────────┤
│ 1   │ B     │ -1.15627  │ 0.466338  │
│ 2   │ A     │ 0.710312  │ 0.799484  │
│ 3   │ A     │ 1.73544   │ 0.280407  │
│ 4   │ A     │ -0.441113 │ 0.372602  │
│ 5   │ B     │ -0.503066 │ 0.509483  │
│ 6   │ A     │ -0.145403 │ 0.856267  │
│ 7   │ B     │ 1.01364   │ 0.259262  │
│ 8   │ A     │ -1.09035  │ 0.720977  │
│ 9   │ A     │ -0.74815  │ 0.475484  │
│ 10  │ B     │ -2.14719  │ 0.636024  │
│ 11  │ B     │ 1.6768    │ 0.35738   │
│ 12  │ A     │ 0.175778  │ 0.271197  │
│ 13  │ B     │ -1.10938  │ 0.03964   │
│ 14  │ A     │ 1.38189   │ 0.0443877 │
│ 15  │ A     │ -1.06808  │ 0.511973  │
│ 16  │ A     │ -0.478153 │ 0.783339  │
│ 17  │ B     │ -1.86331  │ 0.627083  │

In [6]:
# Creating a DataFrame to work with
df8 = DataFrame(Group = rand(["A", "B", "C"], 15),
Variable1 = randn(15), Variable2 = rand(15))

15×3 DataFrames.DataFrame
│ Row │ Group │ Variable1 │ Variable2 │
├─────┼───────┼───────────┼───────────┤
│ 1   │ C     │ 0.907944  │ 0.387976  │
│ 2   │ C     │ -1.00984  │ 0.09704   │
│ 3   │ C     │ -0.203847 │ 0.616882  │
│ 4   │ A     │ -0.680071 │ 0.365912  │
│ 5   │ C     │ 1.91522   │ 0.292043  │
│ 6   │ B     │ 0.0993717 │ 0.424931  │
│ 7   │ C     │ 0.686394  │ 0.120707  │
│ 8   │ C     │ -0.273954 │ 0.681051  │
│ 9   │ C     │ 0.648793  │ 0.254727  │
│ 10  │ A     │ 1.25711   │ 0.0535257 │
│ 11  │ C     │ -0.291172 │ 0.514451  │
│ 12  │ C     │ 0.96904   │ 0.304809  │
│ 13  │ A     │ -0.19308  │ 0.670395  │
│ 14  │ A     │ -0.804071 │ 0.089664  │
│ 15  │ C     │ 1.27671   │ 0.341779  │

In [7]:
# Adding a third column
df8[:Variable3] = randn(15)
df8

15×4 DataFrames.DataFrame
│ Row │ Group │ Variable1 │ Variable2 │ Variable3  │
├─────┼───────┼───────────┼───────────┼────────────┤
│ 1   │ C     │ 0.907944  │ 0.387976  │ -0.522965  │
│ 2   │ C     │ -1.00984  │ 0.09704   │ 0.752763   │
│ 3   │ C     │ -0.203847 │ 0.616882  │ -1.38443   │
│ 4   │ A     │ -0.680071 │ 0.365912  │ 0.767929   │
│ 5   │ C     │ 1.91522   │ 0.292043  │ -0.0715429 │
│ 6   │ B     │ 0.0993717 │ 0.424931  │ -0.139564  │
│ 7   │ C     │ 0.686394  │ 0.120707  │ -0.121889  │
│ 8   │ C     │ -0.273954 │ 0.681051  │ -0.128315  │
│ 9   │ C     │ 0.648793  │ 0.254727  │ -1.27994   │
│ 10  │ A     │ 1.25711   │ 0.0535257 │ -1.21719   │
│ 11  │ C     │ -0.291172 │ 0.514451  │ -0.972099  │
│ 12  │ C     │ 0.96904   │ 0.304809  │ -1.52282   │
│ 13  │ A     │ -0.19308  │ 0.670395  │ 0.428628   │
│ 14  │ A     │ -0.804071 │ 0.089664  │ 0.891061   │
│ 15  │ C     │ 1.27671   │ 0.341779  │ -1.36386   │

In [14]:
df8[3]

15-element Array{Float64,1}:
 0.387976 
 0.09704  
 0.616882 
 0.365912 
 0.292043 
 0.424931 
 0.120707 
 0.681051 
 0.254727 
 0.0535257
 0.514451 
 0.304809 
 0.670395 
 0.089664 
 0.341779 

In [19]:
array1 = Array{Any}(30,[A B C])

LoadError: UndefVarError: A not defined

In [30]:
array_rk1 = Array{Float64}(30,3)

30×3 Array{Float64,2}:
 2.20483e-314  2.20483e-314  2.19849e-314
 2.30425e-314  2.30425e-314  2.19849e-314
 2.20483e-314  2.20483e-314  2.19849e-314
 2.20483e-314  2.30426e-314  2.19849e-314
 2.30425e-314  2.20483e-314  2.19849e-314
 2.20483e-314  2.20483e-314  2.19849e-314
 2.20483e-314  2.20483e-314  2.19849e-314
 2.20483e-314  2.20483e-314  2.19849e-314
 2.30425e-314  2.20483e-314  2.19849e-314
 2.20483e-314  2.30426e-314  2.19849e-314
 2.20483e-314  2.20483e-314  2.19849e-314
 2.19851e-314  2.30426e-314  2.31492e-314
 2.20483e-314  2.20483e-314  2.31492e-314
 ⋮                                       
 2.20483e-314  2.20483e-314  2.31492e-314
 2.20483e-314  2.30426e-314  2.31492e-314
 2.30426e-314  2.20113e-314  2.31493e-314
 2.30426e-314  2.19872e-314  2.31493e-314
 2.20483e-314  2.19872e-314  2.31492e-314
 2.20483e-314  2.19872e-314  2.31493e-314
 2.20483e-314  2.19849e-314  2.31493e-314
 2.20483e-314  2.19849e-314  2.31493e-314
 2.30426e-314  2.19849e-314  2.31493e-314
 2.20483e-3

In [33]:
array_rk1[:,1] = rand(Normal(0, 1), 30)

LoadError: UndefVarError: Normal not defined

In [20]:
array_rk = rand(10:20, 10, 5)

10×5 Array{Int64,2}:
 13  19  12  16  19
 14  11  18  19  14
 12  16  14  20  13
 20  12  19  17  16
 19  11  17  18  11
 13  11  11  16  20
 12  12  19  13  10
 18  14  20  11  16
 11  13  18  19  11
 18  14  19  14  20

In [ ]:
year1 = rand(Normal(67, 10), 100)
year2 = rand(Normal(71, 15), 100);
